export const testData = [
  {
    _id: "1",
    imageName: "example-image-1.jpg",
    imageURL: "http://example.com/image1.jpg",
    diagnosisResult: "Viral",
    confidenceLevel: "High",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "2",
    imageName: "example-image-2.jpg",
    imageURL: "http://example.com/image2.jpg",
    diagnosisResult: "Normal",
    confidenceLevel: "Medium",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "3",
    imageName: "example-image-3.jpg",
    imageURL: "http://example.com/image3.jpg",
    diagnosisResult: "Bacterial",
    confidenceLevel: "Low",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "4",
    imageName: "example-image-3.jpg",
    imageURL: "http://example.com/image3.jpg",
    diagnosisResult: "Bacterial",
    confidenceLevel: "Low",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "5",
    imageName: "example-image-3.jpg",
    imageURL: "http://example.com/image3.jpg",
    diagnosisResult: "Bacterial",
    confidenceLevel: "Low",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "6",
    imageName: "example-image-3.jpg",
    imageURL: "http://example.com/image3.jpg",
    diagnosisResult: "Bacterial",
    confidenceLevel: "Low",
    createdAt: new Date().toISOString(),
  },
  {
    _id: "7",
    imageName: "example-image-3.jpg",
    imageURL: "http://example.com/image3.jpg",
    diagnosisResult: "Bacterial",
    confidenceLevel: "Low",
    createdAt: new Date().toISOString(),
  },
];
