import type { Metadata } from "next";
import { Cabin } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Toaster } from "react-hot-toast";
import { EdgeStoreProvider } from "@/lib/edgestore";

const cabin = Cabin({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MediScan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(cabin.className, "h-screen w-screen")}>
        <EdgeStoreProvider>
          <Toaster position="top-center" />
          {children}
        </EdgeStoreProvider>
      </body>
    </html>
  );
}
